### ISSUE TITLE
Why all fields of data are sorted by lens for easy RNN operations?

### ISSUE THREAD

**Issue by roomylee** [yuhaozhang/tacred-relation#3]
https://github.com/yuhaozhang/tacred-relation/blob/18221efc28be400ad3ec3939f1bbd32ab74b64f5/data/loader.py#L83

Why does rnn operations become easier when I (descending) sort?

**Comment by yuhaozhang** [comment]
Hi @roomylee,

This is mainly because that as of PyTorch v1.0.0 the LSTM implementation requires the input to be batch-sorted by length in descending order (for easier internal optimization); otherwise an error will be raised.

However, the current master version of PyTorch seems to support unsorted input in LSTM by adding setting a `enforce_sorted` argument in `pack_padded_sequence`. So this is not necessary any more.
