### ISSUE TITLE
What is stanford head in the json file?

### ISSUE THREAD

**Issue by TheShadow29** [yuhaozhang/tacred-relation#4]
I am trying to work with a different dataset. I can understand the other keys in the dictionary but I am clueless about `stanford head`. Could you suggest how to generate that?

**Comment by yuhaozhang** [comment]
Hi @TheShadow29, the `stanford_head` field is the index of the head token output by the Stanford dependency parser. It is the same as the `head` field used in the standard [CoNLL-U format files](https://universaldependencies.org/format.html). If you are only using this repo, you can ignore this field, because the position-aware attention model does not need the dependency information.
